const input = `LLBPGtltrGPBMMsLcLMMVMpVRhhfCDTwRwRdTfwDllRRRDhC
gNFJHJFgtZFJjZJHNNFWZWZwwDjCwSDhfCDbdwjfwDTTDT
gmQNZnZNHWnqmQpLtVLMBsPpBqrL
HlHldQtHlctzppdQtjdczHhJRnnhGNVmVRJmVjCVFCNh
LgWNgggZJZGFhCZr
DbqPswwMvDPqzlBNHtzfHdwd
tJgtJwwCtNvPHHPtHzDsdRTsBRDDWgWTgT
QhLQjLGjZQFlFZmnmGLDrzWfRldrTrzTBRWTzs
bFFmFZjhSFHvBCvCvJpb
MSGcvnvMGMJgWJDpdndZwBnppfCp
VPVfQQVbshZNZwdNDwNs
LtLbjmQRLmVhQtTbfgWjJgFFcrqqrGSqWg
fHfCNCwwHfGhcntntrrgHrQnrn
FVqpSpbPpjSVMjqvVmVvMzlzwJnbtnnlzQQlrWzJgt
PTqqRRPSRSmqSpPpSpRZwGCLGscCNLZZZTNdNZ
pQQQslVSVzzCQnZSlplzbLcHZHcrrrbZqFbZjbFm
gWtvPgdMDDtFDHHjJJbbccbrLW
MhNvwwDfDfdtvRQnpFNNTlSRSn
ZTnSnTTzqvFmVzvWWm
ClpCgltHNrtgsHdpLCHtDCNLVvQvVwVmwcsWQGMMQvcGcFcv
JmrgCHCNJtlmHmNhnJjnnnjJhPfhSJ
BgRRZTgHHvRTRmRNLNNhQWlmGFfJlWlhsQshpF
qPqSSttwnnzqqqwtVrPwMthFsJllJJlGhpJhWJQlhVQd
MjMwScnDPzcwjtqDtztnctrvgNZTTvCvLgvQbLbvjTBvBg
SWQSbbqTTbPcfMZSwZZwwn
dghjghmNDmGsGgdnfmtMRCLCCRncfc
pJDJNdsNMMhpssgdprBTBzWlpBWlllWb
TwNLNZTwWCWLwWCSTZSLzWHGrDHHPmGdDHvndGdNfvMm
BgpjtpgjBjVbRjQRhVsDnvgGgPnGdrmvnMDfrf
rhRjRssQJplRtVbpthblbbLSLzFCJZFqLLFWCzqcqzLL
PBrdPMtBPvCQBVBjCfWPqSHbszhGGnsfSG
JpmDwJgWJgNzmShhmfSGzh
pRwNcNpFZNZRWgcNplpjVCMVjdvdMQtCMLZjMZ
lDrcnnlLqLRcDDZRLjFVTHzGCLGVPzGPVWGB
pNwHpdmsNJsbpwsbzJTCPWTVFzzQTWCQ
vbhswdtdwfdsmtNSssHwvllvMcZjnjcnZqlgMDZglM
GVVtJGtzVFsVsDTH
mQRgcBRmRLnBjrtFjCCrHmFF
gqpBnlRpgZcvdSdlMdSvMt
tMSCNGSflffNhnnGqlPPsrzWPrTrVpWr
bZHbmDBQmbDZQdbDcRFZZBTTWWWwqVzszWjrFPVwrzqq
HQBLHmQVQLDdCggMfgMNLvNG
HHNDzNJPJPmdPcNGGGhnhwnVhCQBwBjQ
bsSbLfrLtRSLRSRRRsBwhCpfpCzlwCBVjlCV
zvvsvqLtZqLtzRsqTrggRMHJNWJgHHHNJcgWNPdHcH
qgbNvqbgmmZgZLvZqgnZzlpzpzHtVPzttGPrrnnl
jwswGjQDMsQMjdBwdcjCHVtcPVpCVCrPlVSrpc
GsFWBfhGBfDFDFWqNbLNqbgvqbbvfN
HgwWqtcqHNWgnHcNNCfvJCCJJfJGvnPfrR
sbDhZSmdBbsSdmSDdrjjffRvdjPrprCd
vvZbSFFlFHtqFqqWNc
ZRjnbRsHlncZGjTRTfFVSQBQppQvvFBHpF
zrLwMdhDhqJJttDQSldQVPQSlSfPlV
hCWWCzqWnmcZlRRW
HfgfQflHjWgRQRdRBWVsnbvvscbbbwvmbHncSc
tJGLtPPGZPwVvSSPhw
CLGTLZqJtMGqLDFFDZZJFZJpWjRpVNRWpllDpjlBfgVjlp
rhhGZZhLNhPmfJqvfLlq
dHRTHRHQQWcTCRTHmmjJgfqqlGmgWgql
CCwRzTRRdCCRSQwzRcppprZtrMhGBMZMnDSt
WfffvnSnfSBshwsjhlvGlh
ZHpFNTmppVmNzVVmmFMZzbwwjHGrGlPhCGrljbgHsg
pLZMmqVsZVMMVVscDfdtSSStqcRRdn
RhRbLzRLHLCPmzznHLbzCRTJhdTVSJJVSjdFFNFFNTJv
MGgMfpMsBgpnMtGfnfwBtDBjFVdNSSSFdvJSQSpTJdJjNv
lMsBgDMsblmRblnz
ClNcJZttLfLvvRQzQWwRQN
hrpMdqMspsrGDdMphhdMMMMHBmRWmSVrRVzVTzQBQvSmzVWV
ppHDMGhMMDbGMdDMGbgFbgbMlJJnjjZtZfLPcfcngZfPPfCR
ZRslLRgCclZLZzQghQhfrbfGbJ
pVSHpBBBBDVDqDBldVzfrMzQbfSTSJrzzJrJ
DqqHnBDlpNDVVnpnjtDtNjCvFLcsFFPZRcPsNNmPcFcP
LmLWSmSRNdcpcRHFHrWzWHbMbwZlZlPSbTjlwPbTPJTf
DttBsvhnhqvGGBhGtBVNBVqJlPwslMMPJwTjZbbZPTfbPs
CDthQvVNVFCHHWCFdr
RRtCWSzQZdRMrtRWrSztMggcGDfQTcfFTGqTLgGDLc
bnVhnvPHhhdJJBTLDGcDTcBvvD
pmbnhmPPmHwdCjmdrRtCdj
lTPzwhzmHpTvrDCDHJnsNN
tdgtbMMBbWdFbtqJCnsrqnMMDsrq
FjWdtgLSWttWtLSWtDWBjGGmwGlzTRwPTQGhlQQm
wcbnTtTppNLrntznTBBccCGrVldRrZqdqRCZdFZCVZ
JfHDgjgPPfRRgRlLRddR
jhDhhLMfmJjMjDbNSTzbbbtmttmN
CfGlvzpvpTjzzCWjvDlfvbbJbCRSdSRhsSQCMhdbhR
wqrSmrLHHNcLqrrLBNsndssnnhPshnsQwbnJ
NtcmBLcNVDWzjSvWtv
vZPCSCvCJffvVvmCmPqCSlDSscczHDRcwcHzRlRHHs
LFGFNnGrdQttNMFpzpMRRDslsJwsJH
gjtLnFBJrLvhZvCbZhqB
DBcjVFjDhQMSJVZbHZbl
nfmsqppnLfTnfmMmzppwgllSrbSHHtllqbtSwZ
TRzTnfRWnfdzWssfnRfRpncQPBhdDjjDCPcMQcCBGPPj
NSjWCHjNHjpPWPpSFWdtqBMBBFVBvqvJGJwqBt
gQllgDrnhQQDGRshRsZfVtVMRqwMtccVJcBtvRqw
DQrzrDzhQgrsZLrZjWSSHNTWCjjNGTLH
CgdcCFcbTbBzPgmNRmpptP
rsZtsvVvHZZzPmqVNPzNmV
HZjrwrjnjtHSHwDGdFhCdhWWJnWchCFJ
RMTqQMRJqPtBtGBPtWjN
ssHfSfShCwwbhsbHhhsmSfhSGNpCpNCjBBBLptcGtpzBBBWW
HnwrSFwffHsFwrSSjfHglJJlTgZdFdgZRZTDDM
pDLDWlDSlJDmzSJnDScRPLGGvqFqLPccGLgv
CZHfwNMVNjsHNNqPgcbcBbRQGQ
dCffZCjVCdCHHTmnlSgTlTSrlStp
bFtlLCvLlVjpCGPJndrrMMCDDCnrMg
hRsTwcZcBjZRJrfMDnsHrJnH
mNZqcTSSBTScNzVQFtGtjpFtjmGG
bjHdLrHjRWpDCtLzhzps
lZcGfTvQcQfvlqqcNCcBvVwtGzmzthmwmpthMDmswgMt
NcqflNQTBTTvvQSvqSVvQJbHPHbHCRJdndJPSHjWHb
CVmRncrRVrhcmsBgfmtfdJsJmt
bZHvZZDJwpWtdZgtGNGd
vSbwHDMFMJqPQqQvvSPQqpSwjRcTVTLjLRhVCLFLjLFnFzCC
mtffsmBwfwBDBmmsLsHqtpftGrMVMPSMPsVvhNvFrGPMvjNV
TQTQCRWjJcdcQQSPrhhPSvVGPF
cTRJCnldWJZlTgbWgbdbpqfqmppjmtljpqzmjpLw
NNPmrmPWmrSSNNPmnglghmCvLCCflh
LFbsDQMQFtQFHbQHqhvnngCftpcllptJgJ
bDjsGqLLdRVjPZPP
tgrbBQlbtRblwtRGrbCNswDDCsvFszpssCss
SJVMhSZfHvpdhphN
SMLpWZSSZMjfgGBgRtbQgljQ
HsHHNDDHzHDDjsVBBZqtWBrSNcPwQvccvvdhPclSrQSc
fGCFCgpgTfnTmgTFLFgccclhwQhwrzSwSwrCrr
pmLJGfMRpFmfFMzmgGmRpgmVqWJDqZqqHtjBBVDBBqqssJ
mBTfcfCCmpBCCSzNQScQSTfddhdtwgttjghNwGtGdgwGtd
HvvqbvMLnFZVVPjJGRGzGRjZtwgw
VFHFbsFHHSmzQBmsmT
ZNmZCmNHHzzmPPzlbplvhbQh
GDSwldfdvggPfLvQ
ddqrtlnJDJlnjScRmMRCFHTHtFZF
FPvglHSPcpNcFNSHFHNvZjdmbwdbzZtzsHDzbsbj
MMnBLCCWBJCnrCVWCBstTZdZmdTtbDLswTtZ
BMDnRCrnGhPPSgcgpG
nsbgpbdrjMdGqnNRRWWRww
tZZhPzCJhsJBtJPllJBCtCvwwcwwWLvWvwWRThcGcqLq
mlBmZQPZmlppbgMmfssg
RFdZTHFCdvjhgGnFqj
zQLtNQpzNNtNpDtDPWLNMmGfBcjgjlgjhBnvcfnBvfjp
PtmLsPzQVWzWDswCSwHbRZsGZw
nPsfnPsFhTGjqGnmQppG
RZhBbNwbBRZHZSCCHQqSpCpqqm
VMbgNWRWMDfhtFJT
RWhRPDhBHZWgZghRZwZgGJPGdncFdLcdLCjscFcjCjNLLj
mQfSrlfTVqmSVTTTrprfFLqcdLHsLHFnvsFFqnNd
TtQmVHmMrbMWRggRPJZP
TTlCTVTdcpBlcchF
ZLhwSMZhqhtqwqLjFcBvFmvvssGBmmjj
LwSMRtqMHnqhhRZRRtJSVTgggVPdTdrVbQDJgTPW
CGFFWFFVgjfzgVfcJCcgTCcBBWqSqMMBMBShhwMLMwSSMq
fmQnflldltBZqlwqNZpB
dvtnvmtRtsPbzCfTHjHcPzGf
hzshzfshVhthgMmRsFRvFqmm
PDDcZWlWBbplvmRRGtlvqQ
ncjnDjbScnBWZjDVfwjfrrVtwLjzhr
QRWvffVVGfDhNNjzGZLLcGGZ
rgtpSSHpPrHSspvNLFlzTgNLlFglcc
SSpbMHpvmwMQhMBR
dHLtBqPCtPBHNsbRNdNNsZVN
nQwntMwJWhwWjvcjDMlntRsNpgSbNNpglFpVggbSVF
QDhJWwhzJtTqLzCmtT
PSLqTqrCrRvCSJWLdLwdVWdQWL
zNjHQnnHjHznnbDMnMMMdVZcpZZJpZWcdJFZ
BntfgNbzfBtHzgnbbbPPSstlQSSGGrlGsrTT
QpBNsBzztgqVtdmp
jvrhGljRhSTlGGvjwjSwGjRvHVdqLttrMgMbtMMMVmdqqHfV
ChTvTvljmCsQQQnNsQ
CQCNSQHHgCtNHCNHHNDJcBJwLPtJBGhMPPPJwM
zRTqmsdRRzrmdzVRpzPwcjdwwhLjMBMGBBLw
hprmzRmblTzTVTVrlbrmVHNWNnCZFWNNFZlnDFSWgQ
hGGqwwdwMqsRDGRBzlvDzB
LTNTfcCFFFCcNHFFBzRSZRBlzHPSZdvD
nLVTFNfVVLLWnwnwdrdbhnrhrr
hlTpcDTpHmHwDmMbbdMMMGTPdGPR
ZzFqNSQqHvBvzzqjFHtvSGRRMPQsJGJWRGWPMRdRsM
BZjLNqNqzVVHgLVgll
ZHHBzSZPVqghJgSnBhqJRQLRRMvQpwZvfNQRMMMp
ctFCDmdDWmDGNRFMpRlwwQPP
PrsmDmCGjtcmdjGtVqBSjJhnSbHnnghH
QmZHTjmmHRmmdPRvHdVlPdrNNLqWzffbRtqpzfWtWsWNNW
gwMcgnMGFGCjJLqfbtNtzzssCW
DwMFGBwcBFjhBBhcDSJQQVQTPldTvPlVVZQSdQ
NRTGfNffLghStLRR
QlnWsdJWmnbWnVqWbWqHPSpmjgCjtSwhPjgtptLS
JWchnllHqQJzGTZfTcFNDN
VtdtcTVVCRctVdJclCVtpphpPhNGDwNPmThwWmgG
ZjZMFnfBqqMjHZHMzBnzgPGwDmhmhDPfQNGPQGfD
BbgsnFgMgMlVdJtlcVSs
tlBMdBnClhLJnTbgph
PhDDczqDGPqsHGrRGPWHGPzcFJNLTTJZLNbNLfFZgTbffL
sHsmzzrGmPrRDRHqhHwmjBVtllwtdMdBSBtl
QscfZsGsVjVtqGmlzvRMvl
ThJNCHPTDDhHHJTJPHmlSMTtTTlBvlnMSzqn
HhCdrHrCcpmmdVmb
WPPBPvRWzvhWhWzGWtBqBSTLDZhgFSTCDgSgZZDCZs
flbJmMJnjdMqNdfZZrFZZNFZgrrsTZ
nQnqJlJdlQMMbVnVmdMplVnnBwcBPGttzQcvtHcWwWtHRHvB
LLsmpJTWCJmJppCmgHCCLjbFtRFghzjfjcjcZttbRg
SZlMPBdBtQfFSbSF
nPqldlDwlBVnvdLWJVsmVNZCCVmJ
HWvNVtHWJjHJsSgHsHzsDsmf
RwZGPFGMQgzpTGSD
PZMlwwqhFPPZqwFhPwnFbMjWJNNBtWNVJlCJJWJjWWzj
frBSzJDtztfNVGwRzVgGhqsV
MPMmjPWGMMmPCQCcbmRwVhTgVwTTqjvRTLww
cFpcMGFplDHfBHFS
gtjhjLffmgjgmbgVfbNdqFJMJMNbbwrwqq
sWHHPSJsHzTZzTGsCdrqCNNddGdGFGRC
ZpzHHTZWzsSSnBBPsTBnLVcpQfcJcQVQDQfcDfQt
qMPqChqjQPRCMqlBrmGmLbPSsTbSvz
nWNHZFVZZttWpfHsGSbBGTbWBSGmSm
nZfpVfdZdtFHnwVHZtNwZhCJRJhcCdDcQhCqDSSCQc
LlwSlZrftFSMpfLCdltTmmmSDmJqmssDVJBmJB
cRcGGhpvDTmTDgsG
nNPcjpWbNzjRRcWhbzWjvnLMddMLCwtdtMttddtrCdMz
NszSsDCMSDzdZpCMCSMpNszfTvJhlvmlmrTfrhlhHPrmhD
FRWBgRjWwqFWQFBBWjVncjRTvJfvvJvVrHhmVrHhmrdJTh
wnwnqwRGFqdbNNtCGpCp
zgsBvPVVDDrDtDgt
nTHldmJQNTTfflcJNrQlHWpmDDFDFhWpWCLtFbphCm
nTTNMlNfHQZTQPGSzVVZSVPSwr
bPLbtPpwsJhlpnhnnLNNZDWhRNzWQrWWffNr
SczqFdFHSTFjmMSMFVqFGCWWNRrWQQQRZCVWgQQgrZ
dFdzFGHvjmqGMFwwLLsPnvBspnsn
lwJwwmblVdvjbbbJvVnlmjGTTNTLqffpqDJffqGLqDLD
ZtWgPtRMtQRQnTGDQNTTqL
gCztMgWgchHhvwlllbnl
cCwSSCVbqwCCWSbZMmGdtBllWBfdlvdt
jzRsJjhPjnLthJNNpmpvmvvMfGvjQpGv
nPHPFgRHLtCHZrqTcq
dVJwCJGCVrQQGTNtLtGm
hWWgDHBzWWWpZlhWBssLDTDsQTLLtswswL
gPhBHpjwHcljpggwwWqvbFvdCVRqPPnnqVRb
zRRRRNqzpQZNNRRmRcZscQcCDmCTTTDGfTbfGhrTCTrbFF
HMvMtjgtLHVlLVfhCGfrfhJhhrvh
LBgStjnHBjLVgggBgHndnSNNQdNWcQQNGZccwsccdQpw
jLRqmZNGtZtvZvHzPfCvSSzhCP
QbwDVHFrVbDVrDFbzPwSThSfddhWPWzS
rpnFDccHFHtZNmMmRntj
RFVdzzlNtrwSTltb
hHGcqqBcGLQZffHhMwSswSWGrnnbMStC
cgqLBgQgpgbbPbPz
lfcgglhfTvmlBvclbgztnSRtSmttwRJwptWR
FMjDjsdNDjNMQLFFLCMQdtwGGzRwzpGwzdWzzJpGhn
ZQVNsVZMPsVhCQsFCFsHHlqlcBZrHHfBflbHBB
vGGQQdwNCTJfQJHJbM
FFqmzghlzhgqjlFqzZhmhPlRgBDLLRTTcHMbRcJHBLcgRH
qFrPjnhZmqnhZZjhhmpPzZmtvbpwtdvsSCCsGwdNwvwNCp
nrFdSHScdRwvdvRm
NNpPLJJbNbppCvmzbHTbmsTw
fWLHPlPtpMNBgGQgqggQSMGc
BcHtrBcnjflfHslsrnltbTgvMwpWnnWpwwwCwCCRRW
dzGhLSSGDdPNgLLdPWTqWWRMqwRWpvzMMv
VPZZNhhNSSDhLNSLdFZBVgBbjHcgsgfrbBJbfs
VMnWjjWTnNNCzzhblbbjlj
FmHwfFHqpDrJzPQLPLbCDs
GrdFfHqqSmmwHSqHfpdMNTtTtZCMMZtTRggGZR
QRlnlTphqNfqdjZNmd
rDtPmGctFrcgDjJcNjvNJNCcNw
bgGDtgDbBWBSBVlblmVmsRMmLM
CcQTQTrrmfQQhZZBpZpSSZ
JFqSvLlLbWggDvDDFHjsdnshBZpjHBBhBW
FgJqNvLRMlMMDDblrtfrTCStmCVtNttz
MRRbbddqtHbMZbqMHHTFTFgwZglWPfgsZWgW
LCcLjzCNGNcvpvLTFPmzlFsfTgFlgs
NhNGcrCGrsrvcDpvVcSbtHQJQbnQbSdHMtJV
bfMfBFcWFsWZHBWRPQpRqdwmMpmddm
rSShvvVTNVhvVCCvThDlSvCwpGCmRmGQmPwmpLRLRdpq
DhRzzVNVVgSzTFcgtnbHnHbfBB
HsTGHHvlvvGTGlHBvlbZstrVrwNjrjVStwVVZR
PPmgcFJPFcFWmWMgdNtVtQZtDVDVdZZjjR
LLqWnMnmNvlBLCTzCT
qTttLqLvGCQqCDlhml
FJjzrRBrpjRWrCwrBrrwpRbbDzgghSmmNhPQhgNshmDSzSNm
bJBrbFRjBVnWBrRBnHLfHGfdVtvHttcCdT
mTzjGPmPPmPNjNBTvlJRlNJzZqrzrSZZSpcZqpgcgcggFr
QWCwwMwWWhVZFbpQDSpSJS
stMMsWwMwVWtwJTNNPvvRmTsNPsl
gGFFNWMMNFTBlLpGpSll
qvccssdDwDbhMhzwHLppTSHLrdBpBVLV
PhJhzhMJzwDJwhZZtZQJCjgWtFjZ
pGqWfqqGcspGqWqppHprpTrzhCzttMBCtbtJmtJbSBvWBt
QDnVPgVPgDCJBMhmBJgv
NlZwFlnnPLLlFwDlDlnPPFFHTMTdMZjTTcjsqqcsdfGdcp
HLzZfHWWQwpgVHjVHr
JlMlMGGDMtJGdtJhqtlccDgVCSTFFSCSDTggpvFTjSgS
JcGRMlthtlVNMJRfzWsPnQsnnZNZns
zVfvMpsbtQmtBlFWBZ
lLSrlNTNRSFRFhhHRmPR
dnSJjjwJJGwwnzVlvpszvccM
SmlcCrpnrnznGzSBBSfzNbtsQsWZQcFbWctcbbZb
JHgwJPjvdghbbWdDZGNLZb
JjghvvhRwhwJVhHTzmfRfzGSMrzBfnGC
JbCmrbnzmntnVJjbCHJJFQFvqgJgQgqLDQ
NGhhhhPMGhWsSSchWlNsCLBBlLFQCgqvgCFFgQBg
PdcNWWcdGdPssPPNTSNNtzbTwjntzbbVwtZpCVnb
tGNgtsNQHsJmwwzddmQw
hMhhDBwMhDDfCRRBjFDDTTWjdWmrmdWqjlmmmjJz
RSpSSBhppDhRncRLswZLGvtGvNcNtL`;

const sampleInput = `vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw`;

let bags = input.split("\n").map(str => str.split('')).map(b => [new Set(b.slice(0, b.length/2)), new Set(b.slice(-b.length/2)) ]);

//for part 2
let fullBags = input.split("\n").map(str => str.split('')).map(b => new Set(b));

//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
function intersection(setA, setB) {
    const _intersection = new Set();
    for (const elem of setB) {
      if (setA.has(elem)) {
        _intersection.add(elem);
      }
    }
    return _intersection;
  }

  function itemValue(c)
  {
    var code = c-"a".charCodeAt()+1;
    if (code < 0)
        code = c-"A".charCodeAt()+1+26;
    return code;
  }

let items = bags.map(b => intersection(b[0], b[1]));
console.log(items);

//part 1
let values = items.map(function(set) {
    var c = Array.from(set.values())[0].charCodeAt();
    return itemValue(c);
});

console.log(values.reduce((prev,curr) => prev+curr));

//part 2
let groups = [];
fullBags.forEach(function (v, index) {
  let groupIndex = Math.floor(index/3);
  if (groups[groupIndex] == undefined) groups[groupIndex] = [];
  groups[groupIndex].push(v); 
});

let items2 = groups.map(g => intersection(g[0], intersection(g[1], g[2])));
let values2 = items2.map(function(set) {
  var c = Array.from(set.values())[0].charCodeAt();
  return itemValue(c);
});
console.log(values2.reduce((prev,curr) => prev+curr));